steps:
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker pull us.gcr.io/$PROJECT_ID/frontend:latest || exit 0"]
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker pull us.gcr.io/$PROJECT_ID/backend:latest || exit 0"]
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker pull us.gcr.io/$PROJECT_ID/reverse-proxy:latest || exit 0"]
- name: "gcr.io/cloud-builders/docker"
  args: [
          "build",
          "-t", "us.gcr.io/$PROJECT_ID/frontend:latest",
          "-f", "frontend/docker/Dockerfile",
          "--cache-from", "us.gcr.io/$PROJECT_ID/frontend:latest",
          "frontend"
        ]
- name: "gcr.io/cloud-builders/docker"
  args: [
          "build",
          "-t", "us.gcr.io/$PROJECT_ID/backend:latest",
          "-f", "backend/docker/Dockerfile",
          "--cache-from", "us.gcr.io/$PROJECT_ID/backend:latest",
          "backend"
        ]
- name: "gcr.io/cloud-builders/docker"
  args: [
          "build",
          "-t", "us.gcr.io/$PROJECT_ID/reverse-proxy:latest",
          "-f", "reverse-proxy/Dockerfile",
          "--cache-from", "us.gcr.io/$PROJECT_ID/reverse-proxy:latest",
          "reverse-proxy"
        ]
- name: "gcr.io/cloud-builders/gcloud"
  args: [
          "compute", "scp",
          "--recurse", "compose",
          "giliev91@instance-1:/mnt/disks/persist/",
          "--zone", "us-east1-b"
        ]
- name: "gcr.io/cloud-builders/gcloud"
  args: [
          "compute", "ssh",
          "giliev91@instance-1", "--zone", "us-east1-b",
          "--command",
          "cd /mnt/disks/persist/compose && ./docker-compose.sh down"
        ]
- name: "gcr.io/cloud-builders/gcloud"
  args: [
          "compute", "ssh",
          "giliev91@instance-1", "--zone", "us-east1-b",
          "--command",
          "cd /mnt/disks/persist/compose && ./docker-compose.sh pull"
        ]
- name: "gcr.io/cloud-builders/gcloud"
  args: [
          "compute", "ssh",
          "giliev91@instance-1", "--zone", "us-east1-b",
          "--command",
          "cd /mnt/disks/persist/compose && ./docker-compose.sh up -d"
        ]

images:
- "us.gcr.io/$PROJECT_ID/frontend:latest"
- "us.gcr.io/$PROJECT_ID/backend:latest"
- "us.gcr.io/$PROJECT_ID/reverse-proxy:latest"

timeout: 600s